name: Markdown to PDF
on:
  push:
    branches:
      - main
  workflow_dispatch:  # Manual trigger
jobs:
  build-pdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: ./
          output_dir: pdfs
          images_dir: ./assets/images
          image_import: assets/images
          build_html: false
      - uses: actions/upload-artifact@v3
        with:
          name: pdfs
          path: pdfs
